Allow overwriting trust policy actions
mineiros-io/terraform-aws-iam-role pull request #22
Opened 2021-02-09 23:35 UTC by allistera

2021-02-09 23:51 UTC, mariux requested changes
hi @allistera, thanks for your awesome contribution. 

If I am not mistaken, I spotted one small issue in the type of the new variable.

2021-02-09 23:51 UTC, mariux commented on variables.tf
> +  }))
This should be set/list of string as we don't use complex objects here, like we did in conditions or principals:

```suggestion
  type = set(string)
```

2021-02-09 23:53 UTC, allistera commented
Hi @mariux  yes good spot! Serves me right for doing a quick copy and paste job :)! I have updated the PR. Thanks

2021-02-10 00:01 UTC, mariux requested changes
my bad, missed something in my last suggestion

2021-02-10 00:41 UTC, allistera commented
Updated. Thanks again

2021-02-10 15:47 UTC, mariux approved these changes

2021-02-10 15:48 UTC, mariux commented
thanks again for the contribution, we will run tests and merge to master and asap released. ;)

2021-02-10 15:49 UTC, merged