Add module_tags and instance_profile_tags
mineiros-io/terraform-aws-iam-role pull request #31
Opened 2021-08-26 07:39 UTC by soerenmartius

2021-08-28 12:07 UTC, mariux requested changes

2021-08-28 12:07 UTC, mariux commented on variables.tf
> +  description = "Key-value map of tags for the IAM instance profile"
```suggestion
  description = "(Optional) Key-value map of tags for the IAM instance profile"
```

2021-08-30 07:38 UTC, soerenmartius commented on variables.tf
> +  description = "Key-value map of tags for the IAM instance profile"
fixed in 204cc6b

2021-08-31 11:44 UTC, mariux approved these changes
lgtm

2021-08-31 11:48 UTC, merged